{{- range $name, $mcp := .Values.mcp }}
{{- if and $mcp.enabled $mcp.autoscaling (kindIs "map" $mcp.autoscaling) $mcp.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "mcp.labels" $ | nindent 4 }}
    app.kubernetes.io/name: {{ $name }}
    component: hpa
    {{- with $mcp.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $mcp.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $name }}
  minReplicas: {{ $mcp.autoscaling.minReplicas | default 1 }}
  maxReplicas: {{ $mcp.autoscaling.maxReplicas | default 10 }}
  {{- if $mcp.autoscaling.metrics }}
  metrics:
    {{- toYaml $mcp.autoscaling.metrics | nindent 4 }}
  {{- else }}
  metrics:
    {{- if $.Values.global.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $.Values.global.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $.Values.global.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $.Values.global.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  {{- end }}
  {{- with $mcp.autoscaling.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
