{{- range $name, $mcp := .Values.mcp }}
{{- if and $mcp.enabled $mcp.persistence (kindIs "map" $mcp.persistence) $mcp.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $name }}-pvc
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "mcp.labels" $ | nindent 4 }}
    app.kubernetes.io/name: {{ $name }}
    component: pvc
    {{- with $mcp.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $mcp.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- if $mcp.persistence.accessModes }}
    {{- toYaml $mcp.persistence.accessModes | nindent 4 }}
    {{- else }}
    - ReadWriteOnce
    {{- end }}
  resources:
    requests:
      storage: {{ $mcp.persistence.size }}
  {{- $storageClass := include "mcp.storageClassName" (dict "mcp" $mcp "global" $.Values.global) }}
  {{- if $storageClass }}
  storageClassName: {{ $storageClass }}
  {{- end }}
{{- end }}
{{- end }}
